### ISSUE TITLE
_bot_ctf.gsc has 3 unresolved externals

### ISSUE THREAD

**Issue by xerxes-at** [JezuzLizard/Recompilable-gscs-for-BO2-zombies-and-multiplayer#13]
**** 3 script error(s):
**** Unresolved external :  "bot_combat_throw_proximity" with 2 parameters in "_bot_ctf" at line 1 ****
**** Unresolved external :  "bot_combat_toss_frag" with 2 parameters in "_bot_ctf" at line 1 ****
**** Unresolved external :  "bot_combat_toss_flash" w

**Comment by JezuzLizard** [comment]
These 3 functions had 1 extra input but the actual functions only could accept and use 1 input. The whole function those 3 functions are called was difficult for the decompilers to decompile so I had to make my own judgments. It shouldn't crash the server anymore on launch.
