### ISSUE TITLE
8 Player Origins - How are Staffs handled?

### ISSUE THREAD

**Issue by chsedotsh** [JezuzLizard/Recompilable-gscs-for-BO2-zombies-and-multiplayer#16]
Do only 4 players get them? Does each staff allow to be picked up twice?

**Comment by JezuzLizard** [comment]
Unfortunately by default the staves are only available to 4 players so while using the 8 p patch the other 4 players will have to make use of the pap for their best weapons. It is possible to modify the mystery box however to give staves.
